### ISSUE TITLE
Following the example i get the following error, can you please help me 

### ISSUE THREAD

**Issue by HenkLaracker** [Seeed-Studio/Grove_Indoor_Environment_Demo#1]
Board Intel:i686:izmir_ec doesn't define a 'build.board' preference. Auto-set to: I686_IZMIR_EC
WARNING: Category '' in library DallasTemperature is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library EEPROM is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library Ethernet is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library EthernetShield is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library OneWire is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library SD is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library SPI is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library Servo is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library SoftwareServo is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library TimerOne is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library USBHost is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library WiFi is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library Wire is not valid. Setting to 'Uncategorized'
Warning: platform.txt from core 'Arduino i686 Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
Grove_Indoor_Environment_Demo:69: error: 'getTempSensorValue' was not declared in this scope
   getTempSensorValue, 
   ^
Grove_Indoor_Environment_Demo:70: error: 'getHumiSensorValue' was not declared in this scope
   getHumiSensorValue, 
   ^
Grove_Indoor_Environment_Demo:71: error: 'getLightSensorValue' was not declared in this scope
   getLightSensorValue, 
   ^
Grove_Indoor_Environment_Demo:72: error: 'getUVSensorValue' was not declared in this scope
   getUVSensorValue, 
   ^
Grove_Indoor_Environment_Demo:73: error: 'getPIRSensorValue' was not declared in this scope
   getPIRSensorValue, 
   ^
Grove_Indoor_Environment_Demo:74: error: 'getMoistrueSensorValue' was not declared in this scope
   getMoistrueSensorValue
   ^
Grove_Indoor_Environment_Demo:79: error: 'RelayHandle' was not declared in this scope
 pActuatorHandler ActuatorHandlerList[]={RelayHandle, BuzzerHandle, ServoHandle, SleepHandle};
                                         ^
Grove_Indoor_Environment_Demo:79: error: 'BuzzerHandle' was not declared in this scope
 pActuatorHandler ActuatorHandlerList[]={RelayHandle, BuzzerHandle, ServoHandle, SleepHandle};
                                                      ^
Grove_Indoor_Environment_Demo:79: error: 'ServoHandle' was not declared in this scope
 pActuatorHandler ActuatorHandlerList[]={RelayHandle, BuzzerHandle, ServoHandle, SleepHandle};
                                                                    ^
Grove_Indoor_Environment_Demo:79: error: 'SleepHandle' was not declared in this scope
 pActuatorHandler ActuatorHandlerList[]={RelayHandle, BuzzerHandle, ServoHandle, SleepHandle};
                                                                                 ^
exit status 1
'getTempSensorValue' was not declared in this scope

**Comment by lanselambor** [comment]
By Adding declaration of functions has solved your problem.
thank you!

**Comment by authenticfake** [comment]
during the compile phase I receive the following error message 
In file included from Grove_Indoor_Environment_Demo.ino:15:0:
/Users/a.franco/Documents/Arduino/libraries/Grove_Indoor_Environment_Demo-master/TH02_dev.h:38:18: fatal error: Wire.h: No such file or directory
 #include <Wire.h>
                  ^
compilation terminated.
Multiple libraries were found for "Dhcp.h"
 Used: /Users/a.franco/Library/Arduino15/packages/Intel/hardware/i686/1.6.7+1.0/libraries/WiFi
 Not used: /Users/a.franco/Library/Arduino15/packages/Intel/hardware/i686/1.6.7+1.0/libraries/Ethernet
 Not used: /Applications/Arduino.app/Contents/Java/libraries/Ethernet
Error compiling.
