### ISSUE TITLE
Certainly I don't know what I'm doing...

### ISSUE THREAD

**Issue by Waferboy** [Seeed-Studio/Grove_Indoor_Environment_Demo#2]
Hoping to get some help from someone.  Completely new to this stuff and it shows.  Everytime I go to upload or verify the Indoor Environment Demo file I get an error for the TimerOne.h file.  Can one of you smart folks help me out?  The error file is uploaded.  

[error.txt](https://github.com/Seeed-Studio/Grove_Indoor_Environment_Demo/files/863534/error.txt)

Thanks ahead of time.

Waferboy

**Comment by lanselambor** [comment]
@Waferboy please change to Intel Edison board in Arduino IDE the tools and boards option.

**Comment by yonghuming** [comment]
any version that support arduino
